### PR TITLE
Prevent partitionfinder crash when passing in a single partition.

### PR DESCRIPTION
**Pull request by biologyguy**
This allows partitionfinder to be used as a straight-up wrapper for model testing on a given alignment.

### CODE REVIEW

**Comment by biologyguy** [comment]
My PyTest is failing on 39 tests before making any changes, so I can't really tell if this commit has any deeper influence than intended. Hopefully someone with the correct dev setup can run the full test suite properly.
To put the issue in perspective, below are the alignment file, .cgf, and partitionfinderprotein output behind the pull request.

```phylip
 16 700
ovizSpMB  M--------AESGKDAIAALESTTEKNEHNLVIEFGTDRILHYAGVYL---VAFLASLAKI-VQLASGNITC--YP--------AGD---KQASS-DFIKYANSYCWESSA-------SITNASNVSCGGL-----PNTAIFIAEPDRLKAIFRALPYLMIFEALLYALPSIYWHSLVGAKLMGHLKFMKNLLTD-IYEIVQKIPR--------GIYKSDSSYDSDSYYLNGWNGFKPDYRTRQ-----RSRTASSSNEEGRNLLENDG--------------------------------------------------------------------------------------------------------QPKATKEKNFYER----LLGD-MKDRHLFSMLCFENFSSMEHHPYILSVYHLSRAPTTSPDEAFI------------------GSKIKGMLRLVTNKNNFG-GRFLVKAYFCRHIIGVIVSLIAVLTLFWILA---WIGADGWQAESFRCDVVHHE----------DICMICTFLRKFDMLGYIIINLCISLMYLVISLSRLYFIR-GSS-ERAICHYFEEISDTG------------------SAALNKVE---------------------------------------------------------------------------
KTeEPNYs  M-------ASMDTGDTIRALENAAEKHEHNLVIEFAMDRILYYVGVYL---VAFFASLAKI-IQLAAENITC--YP--------AGG---GNPSR-HFIRYANSYCWESSR-------GTVNVTDHSCGVL-----PTTLAIIKDPDNLKLIFRVMPYVMLAEALLYALPNIYWHYRVGARVMGHLKFMKHLLND-IYLTVQKIPR--------GIYTRGKSYDESSYYLNPLNGYSPNPPDGG-----EKKKKSSQELDSRGRCSVSR--------------------------------------------------------------------------------------------------------NVSETKCKDS-------LYRG-MKDRHLFSMLCFENFSSMEHHPYIVSVYHLLEKPEPSPDDSFD------------------DAKIKGMLRLHTNNKNFN-GRFLIKEYLRRHIIGVIVSLIVVLATTWIMI--WTIGFEDLHAESFRCDVMHHE----------DICMVCTFLRKFDMLGLMIINLVIGAIYLSMSIYQICFIR-AGP-ERPICGYYEEISDVG------------------FAALDEDVDMEDSPPVPEVPVRPLSEDLSSRSNRQSQPPTQPAPDNTAAL---------------------------------
ftsYXyvq  M-----ATAESAAKPAVDKLVELAKQHETNLVVDLGVDRLLHWISVYL---FLALGILVKV-VDLATTSLSC--YP--------LDP--SQSGNS-HLITFAQSYCWLTYE---------TPINASECNYNNSVPWSSNPQDSQNATMLKILVVLMPYWLVIQAIIFALPLTYWHTRFGARLTGHLKFVELLLKQ-IYEQVSAVKN--------GYY-HKKPYDANSKNFDGLCDFEPVSFSESTQK--AKCKVPSTNPFQQGSSSSQKVLSSSQKSTASGEMLVQVESDELKPLVTTTSAAAGSSSQKSTLPGETIIQMKSEESKPLVTTNNAATG---------------SSTREEPSSRRSTSTGETQTQVVTEEKPISQFTKF---IVGD-MRDRSFFSMLCYENFSTLFHIPYILSVFELNKSDKQKEPEADQ------------------YKLNESLLYLWCNDDNLNKGTLLIKKYLLKHLFTALIAAVMIFLMIIFAL---AAGSELNSNGTFGC-LLPYD----------EACMLCTILSKRDTFAVFICDLAITSIVMVVSFINFWEVR-RSK-SRNTCHFFDLLKQRT------------------TYVFLKTGDEFPNI---------------------------------------------------------------------
6RYgZM8o  M------TTVTSGQNVISGLEKASQQHEVDLVIDLGVDRLIKWIGVYA---ILAVAVVAKI-SDYVGPNLSC--YP--------AGN--SSGYDG-NFIEFAKTYCWESVTSYETASVSTSSNTSQRCAFLNS---NGENDLLKNPKNLKIFIHWLPYLMLLQAFVFALPSAYWHFRVGARLLGHIKFMQLMITD-IFDKVKIIPL--------AFY-EGTAYDEKSENFDGLRRFRPKQKESVTQ---SPSASPSKPAVDLNTTSASN--NSNTSEEPHEDLHVIVVGKESSPLIRKRSTTSHSNSATEEVGTSRKVSPSDIELQPVGGSEQNNVIA--------------DHAPENPSNTQTENTSKNIQESKDPTKQVSFLDWL---LSGN-MKDRHLFSMICYENFASMHHLPYILSVFNLQAFTPEGGFEDEVYEPEIDKQ----------YPLTESLLYHWCHGKNFN-NTFLVWNYALKLIFTAVSAFIMLAVMVWSAI---ILHDDMAASETFRC-QLPYQ----------DLCVLCAIKRKRDIYAMFWCDFTFTLVIFVLSLSYWLLGR-TGE-NRATCHFFDRMKQTC------------------NVALGTAAVTAQKSQQ-------------------------------------------------------------------
OxlGsUF7  M------PQETVTENLQANLERASQLHENELVIELGIDRFLKWLGVYT---ILVIALVAKI-SEFTGPSTSC--YP--------AYN--TSGYDR-KFIEYATSFCWESVT-------TSDITTPEGCLVEDV---KSNTKLLPNPKAAIYFIRWLPQVMLVQAFLFAVPSICWHFVVGGRLVGHVRFIQLLLND-MYEAFRKLPT--------AEY-GNKPYDKSSECFNGFRKRQERTNG-------SETLMAQQPKEQHNLSLKKD--------------------EEEGKLLRVVEATTHKKDVESTSVTTHSLKTSK--------------------------------------------------------------------LVGD-LKDRHLFSMLCYENFSSLSHLPYILSVFHITKDEAEKKRQEKKKKEEKKKGGNEGKEEKQIIPMQHGMLKLWCNENNLG-GTFLVKAYVVKHCATLLLSIALLISFAAWASADGVLQALLGSSNTYTC-KVAFQ----------DVCMVCVVNRAQEIMFMFICDLIITIFIMVLSLGWVIFFR-MCSIKRVMCYFFEHLTDTC------------------TLAFLTLNSYMKGNNDE------------------------------------------------------------------
eQyTNyyv  MEEKPSKGSASFGETVFAGLERASQQHESDLVIDLGVDRLLHWIGVYA---TIGLALVAKV-SMYIDPNLSC--FP--------TEK-ISIEYTV-PFIAFADTYCWGSPK----------AETNSMCHL--P---NNSTSLMKNPEVFISFIQWFPYMTLFQGLMLATPNAIWHFLVGGRLYGHLKFVKLLIKT-MFDKFEKLTG--------VYY-RQTAYDTDGESFDDLKKHLSKDKVNE-----ESSRDESRPMHKVNLVKSNS-----VVETSFINPEVPLSPTPSSPTLESDEIETPINETGPGAEESGKSAFESVRCCNVFTRLMRPCQVCCRKRPYKITDDHIALVKVKTQEAQKAECSKNLIENKEDTNKRNSLERFWDRVLGQ-MRDRHLFSMICFENFASMQHLPYILSVFKLIPPVNDRRKKKRGETPGR-------------LPLHEGMLYLWCHKDNFQ-TTFLVKRYTVKHLCTALFAYIWLVIMIYLGN---VSWDSPRDTDTFPC-ILPGN----------TICILCTLKGKSDILALLICDCVILTTVSLVSLFYWIFWR-IGS-ERANCKFFEKLNSDS------------------TTAFQQTETAEDFERDHKAVHDGRAQFNEEMTNFMKNMEKLAMNLLSGRKVTAKDSS--------------------------
DPzeCFv7  M----NAIFDLFKTTAVGAFESVSRDHEKDIVIDLGTDRFIKYLVTYI---LGILAVLVAS-YALIGPVTTC--NP--------YNQ----TYSV-AANDFTNTYCWNS-----------DPYTNEICRDLNR---SHMAQALDNHMDIRHFYYWFPYFLFLQILLFLLPWTYWHSRMGSRLTGQLKYMKVLSNA-LYDTLKGATK--------GWH-VNEPYDRSSSWLNGNKTYKE-----------PPFIYASNPNISETINETLN----------------CDKNALPKPLLETAQHS----------------------------------------------------------------------QNKWWKKIKTSLNKI---VAGQ-LKDRHIFSIFCFENVTSLEYLPFIVTSFNADALKEESLKQNIGY-----------------YSLSASLLYLYTHEKNFS-NCILATVYLWKHVVTALIALASLITITCWNF----LHATDEELQFFEC-YLPNR----------NACVICSIPSQREMRVLMWVDIVCLLIIFLSSVQHWITTR-NSW-KKEKCRYLDIIKRYY------------------KLEKHEIREKNKPVRED------------------------------------------------------------------
R1RlsUSq  M---------SDQSAVLVSLQQQSEKHEKEIVTDLGTDRVLNFIGLYG---LTGLAVLCQLASSLSGSNLLC--YP--------EDE--NTTSDG-AFLTFASSHCWSNTS-------------------LLS---TSNEELTAQLITQNTLALWLPLFMFFQALLFCVPNFYWHFNVTGRLLGHLKFMNVLLKN-IYDKVKILRQ--------GRY-ELEPYDKTGEIINATYKVNE-----------PSGIKQRKRKDELNDVKVNP--------------DNNKTVDEKRKLVKGDDAPKDKHPTDKTAPPREDVGWLDCL------------------------------------------------------------------LYGKVLTDRHVFSLFCDENFSNMDYYAYILSVKKLTKLIGVNTKDEKKF-----------------YPMLQAMLKLWMNKENLT-SRTMAKRYTIKHIGGMLLAILFIVVYVLYFL----YLWDAIHINSVQC-TIPN-----------YGTLVCDFKNSHQVLLFIVLNMFILVVHLGFSVYHLRFLR-NCD-GLPCCDFFKDFRESS------------------DIALFAAYEQERLERE-LNQATSEQENKSTTPSTNKATSEQGNKSTTSPTSQAASEQDNKATTSPTNQATSEQINNRIN----
dWpDPG0D  M----------DPAGFISALGDESSKNQHQVVTEFVEDTAIHFIGCYG---FLLIGLILQL-SGSIQEQINC--IN--------SKSPVENAFSR-DTTTFVNNFCWMAEN----------DDSNTFLTFENQ---D---------LDARWYVDHLSKIFFLVAILFHVPKICWNMSVGGILNSYMGYTRLLLDI-VKQKLESIPKDGIWGGTEKYH-PARAFDPESKLFSQHQTYIPLRMDKFLKDVGEGDASLEDMLESSTTSSIKN---NETGCFDCRGSSKDTNRDAENPLMGESDESICCLGNSCKNVCK--------------------------------------------------------------------------------MNDRALVGKLMYRNFSHMNVIPLIVSIHKVTYMQDSGTGHHEFLYDKKTGKPNSHIPIYR-HGVLWCILKMWACEGNFN-GSVLYKKYLYKTTFNFILSSSLLASSCFYGR--KFLVGPDDIPEEMKC-VISAQ----------QIEATCILPTVGDVYIPIIIAIFFLAITTLLSFYVIVTVFIKPNTSSVGYNFLSYIFDDA----------------LGYSVLWQRPNTSELQKQ-MMKASVDAETPVIILPTEKK----------------------------------------------
R8YTsQvx  M----GVFGLVDPSNVLGKLSGETKRNRSLPFLMLNADRVFIHFIAAVPSLILTAAVLLGD-KMYSSNSLVM--MT--------PTINGSRPFDRWYDQPAITEYCWSQMKAVKVS--PNGEVLETN----------------------IWHYSMFPYVMVMFCLIPLLANLAWRVMDLDELAHALDFIIDGVEESIQDTVAFL------------------IKRA-----------------------KSNGRLESPAGATSMTENTA--------------------------------------------------------------------------------------------------------------------------------------------FIQPNLYKDYVSSFKVEK-----------------------------FQEFNLILNKYSKQAEFR-LKLKILRIVS-------LCCVLIENVLCYYI----YLVPESNPVTFGC-YLPRELQISSG----QDIGYFIFSPVTTRSLLLWSMFYLNWLVLGFGLFSFFLNPKAPA-KNPGVQLIDNLPQID--------DDLKFDESNDLLYILSLVHTNRFRYE-SLRFGFHILAVSKLATSDS------DAKHQEFLKAMRESALWEAT-RNSSDEIIAGINQNVKL---
e4FeYNoS  M----GILGIIKPDSYLEKFSRESKRHESLPYIMHKPDRLLLHLLVSIYALASAGAVTVGL-DLYRKSGLSF--VN--------TKVNGSKIYDS-DEISEMLDYCWSHFNHED----ENGNVHE------------------------LWHFRLFPYTLVVITIAISCAQISWRAMNFDEAIHALDYIIDGLEESINDVIVQM---------------QNAMKKADAG--------------------RRFASITVDGAGSTLSDASD--ENSATFLVAKSSKDVLDLDSSKPLKTE-------------------------------------------------------------------------------------------------LHSRKGYGSLRKTNDCD------YVTLDKLYAQIAENDDWK--------------------FANFNKILLRYYKRSSFR-LKFIVLRTLT-------FLLVFFSNFFIYYQ----LIAPIRNPTTISC-PIPVELQHIRN----VKREKFEFSNTETRVLLALVTFSVTTAVLAGGMIMWILTP--AW-DNGGIKLVEVLPVLR----NKEIKRMRRGVWNDLIYLLSLVHVNRFRSL-ELRVAFYVLAVSEQLPADDGDDSSVESRKKKFIKLMMELMAWPSDSDDGVKSRLESIADNLV----
o80j6Nk8  M--------------------LTAKKHQY----QFRGDRVVSWITVLSPITILLFIVLFLP-AVFSIDGLQIKGIP--------DLPSNSSWDTG-KDLPYIRSFCWAHMSHFDID--TNGKIIDTS-------------------KISLDHYQFLPAFMLMVCTVFIGVEIFWWVGEIERVPFHVDYFINCLEDAFEEFGRTLLL-------------ERTTDH------------------------SKAKTVGNSTCEESDRSGIN--------------------DENAPILSYRISTGS------------------------------------------------------------------------------------------------------------------LTNSELLEIYHEQKTDRN--------------------FSNFELFVQRMARSQDLV-KTIFARRILR-------FFALFIINVTLYLI----YLNPTRQLHEFRC-PLPEAYRIDGAEGAVQETVQALFSGVSQRTLLLSAYFCINLLTLITLPFCWTVSC--AA-WRRGYNLLFCLPFGE-----VLKDQKQQLKVSDLHFLMALAEMNRTPHW-CFNLAVETINSIPLRDQKRFFLSAFREVLRRRVTATGPPVTLSRQKTDSLRDIPDNIMGSNI----
oh4LGxqc  M----SIPAFAAAAAYKATETLQKKKSHVTLNPVFKNDRFITTLLTAAPVMALSVLLVIAP-AGFTPEILTC--SLRTKKIN--ETSSSCDTFHV-ADHSFINNYCFSRMAHYEVD--EIGNVDLES-------------------KTTLRFLKLFPYILLALTTLGAWTGICWEMTSSKRI-GQAEYLMDGIEEATGELIAGLKAVSNILNKPKKKILQENMDKKSIYGSMMSINKAGQEQRQAMRHNRQARASVRQRIASNLTRETS--KCQDKLNGLPVRKRSVSGAEDDPLKIDMKVEDDVISMKEPQKPLGTMAIRE-----------------------------------------------------------------------------------CTKNLSSTIY-------ESLEDHWKKNDTRAK-------------------FMELEDLMEARAGSSDFL-ATIYLNRLNC-------LICNIVGGGVLFNW----FVYRIFDLDSFNC-LLPEYYHYETSNGEFWQTTRCYFKPLGSWLLVSFLTFTLYCFTFMLQLYFWYLSH--KK-WKTVYTLIQYLPITC---------AVAEDSLSDLHVLMAKISENDGARK-TLSMCDKVLSALNKSEHEK------------FLLVLLEVIVWGET-DEKVDGLVSKILRAK-----
oPET3ycS  --------MLSLAADAIFANAKTNTGDTKVSKASLPNDNIITLLAVGSPILLISFALVFSP-NLATENGLRC--AP---------------TSPM-KNRFYMYNYCWENFNHYELNFTEEGIVEIGE-------------------PRWMIHHKAFPYAFFLVSFILSMPAIYWVLGYSDNVKRQATYIMSGLEEALALTLSLM---------------SDLVQE-----------------------------KDEEKSAENVKDRMN---------------------------------------------------------------------------------------------------------------------------------------------------------AMLEKNYSEEIDIK--------------------FKAFKKYLQKKNSSTKLA-RAFIQRRVFT-------LILLILVGIFMYEI------YYLDNQDYFNC-KLKYQPLGTEVQEG-ISYVRCSIGDVSTRRLLVQIYLAVIGACFVGIFVITIKDA--LN-AHRAFKLLEMIPIID---ENEIHNSANFFGLRDIHILLFLAKSNFSENE-LFKTCHRAYEMSRMTNIP-------------YENMIETIVSWGEE--DEADKDAA-----------
gdV6uH8T  M------VLVQDIESTLLGGKEINDILEA-TVSTLPADRLLAQIGVGLPILLLAAAIVIDP-SLNKQSSLEC--AP-------------YGDEGY-TDGLYNQNYCWERLQ-------TLGTTNTTS-------------------DGHFQYHKMFPYLLFGLAFVVFIPHCLFTLVYQEKIRMHSVFMMSALEEGIFEMFSAI---------------KTLLNEDGG---------------------KNELKVTREKIREIFEKSAK--------------------------------------------------------------------------------------------------------------------------------------------------------SWELDK-----------------------------FEMFEKYVKVERGTLVLT-MGLALRRLLT-------LAALALDGIILYFL------IMQHHSDQVFC-PIINHPHGE------QRGYYCTVSDIGPRLFICRVYISGIFASLLAGSWSFLKDL--SE-INKAKDVLELCPLIDENIYSKEISSNDICGINDLNILLLLVRENFADTK-AMKFCLDAKKLADETNAD-------------YLNVLVAKIAWKLN--DSLDEAYKETNIIAE----
muDZEOuG  --------MIQDAATWIWGQAGADKASQAAKTTQYAVDKFVTFISVAAPIILVVFTRQYAP-NIGQSSGLLC--APPVSSGYTLNGVTGVAGDGF-TEMFYMQNYCWESFKSFPVK--SVNIYGETIAVF-------DDDETRAEQIKSLELLKVFPYVMMAYAALMFLPFLVWSRMFATKTRDQLDFLMGGMEEGLTMTIGGL---------------AKSLDG------------------------YKGRRLERTTDEETVYQALA---------------------------------------------------------------------------------------------------------------------------------------------------------KELQK--DPNLNEK--------------------FESYQKFLLTLAKSNSLS-IGYSMRRWLH-------AIITVTCTYFLFVT------YVQDYQSSFNC-LLNWTVSGNGDKDVISPAVLCSMQGVELVRLVVALICALNTVLVPFYAIMAFYTW--GE-TRKAIRTLQMLPSPVIIQYSEIYEAAESLKCSDLHTLLSLAKNSLREVHPTFAFCVQASKMARTLNGKK--KKPDGDDDGGYLVMLKGLVAWGKK--EAEDTKREAILKNLRHHGK
```

```config
## ALIGNMENT FILE ##
alignment = MAFFT_Urochordate_Panxs_hashed.phy;

## BRANCHLENGTHS: linked | unlinked ##
branchlengths = linked;

## MODELS OF EVOLUTION for PartitionFinder: all | raxml | mrbayes | beast | <list> ##
##              for PartitionFinderProtein: all_protein | <list> ##
models = all;

# MODEL SELECCTION: AIC | AICc | BIC #
model_selection = AIC;

## DATA BLOCKS: see manual for how to define ##
[data_blocks]
align1 = 1-700;

## SCHEMES, search: all | greedy | rcluster | hcluster | user ##
[schemes]
search = greedy;
```

```
(py27)bondsr: [MAFFT_Urochordate_Panxs] $ partitionfinderprotein ./
INFO     | 2016-03-08 11:53:57,133 | ------------- PartitionFinderProtein 2.0.0 -----------------
INFO     | 2016-03-08 11:53:57,133 | You have Python version 2.7
INFO     | 2016-03-08 11:53:57,134 | Command-line arguments used: /usr/local/bioinf_tools/partitionfinder_git/PartitionFinderProtein.py ./
INFO     | 2016-03-08 11:53:57,134 | ------------- Configuring Parameters -------------
INFO     | 2016-03-08 11:53:57,134 | Setting datatype to 'protein'
INFO     | 2016-03-08 11:53:57,134 | Setting phylogeny program to 'phyml'
INFO     | 2016-03-08 11:53:57,134 | Program path is here /usr/local/bioinf_tools/partitionfinder_git/programs
INFO     | 2016-03-08 11:53:57,135 | Setting working folder to: '/Users/bondsr/Documents/Work/Innexin_evolution/Sequences/Deuterostomes/Urochordates/ancestral_recon/partitionfinder/MAFFT_Urochordate_Panxs'
INFO     | 2016-03-08 11:53:57,135 | Loading configuration at './partition_finder.cfg'
INFO     | 2016-03-08 11:53:57,143 | Setting 'alignment' to 'MAFFT_Urochordate_Panxs_hashed.phy'
INFO     | 2016-03-08 11:53:57,143 | Setting 'branchlengths' to 'linked'
INFO     | 2016-03-08 11:53:57,144 | You set 'models' to: all
INFO     | 2016-03-08 11:53:57,466 | This analysis will use the following 112 models of molecular evolution
INFO     | 2016-03-08 11:53:57,466 | LG, WAG, MTREV, DAYHOFF, DCMUT, JTT, VT, BLOSUM62, CPREV, RTREV, MTMAM, MTART, HIVB, HIVW, LG+F, WAG+F, MTREV+F, DAYHOFF+F, DCMUT+F, JTT+F, VT+F, BLOSUM62+F, CPREV+F, RTREV+F, MTMAM+F, MTART+F, HIVB+F, HIVW+F, LG+G, WAG+G, MTREV+G, DAYHOFF+G, DCMUT+G, JTT+G, VT+G, BLOSUM62+G, CPREV+G, RTREV+G, MTMAM+G, MTART+G, HIVB+G, HIVW+G, LG+G+F, WAG+G+F, MTREV+G+F, DAYHOFF+G+F, DCMUT+G+F, JTT+G+F, VT+G+F, BLOSUM62+G+F, CPREV+G+F, RTREV+G+F, MTMAM+G+F, MTART+G+F, HIVB+G+F, HIVW+G+F, LG+I, WAG+I, MTREV+I, DAYHOFF+I, DCMUT+I, JTT+I, VT+I, BLOSUM62+I, CPREV+I, RTREV+I, MTMAM+I, MTART+I, HIVB+I, HIVW+I, LG+I+F, WAG+I+F, MTREV+I+F, DAYHOFF+I+F, DCMUT+I+F, JTT+I+F, VT+I+F, BLOSUM62+I+F, CPREV+I+F, RTREV+I+F, MTMAM+I+F, MTART+I+F, HIVB+I+F, HIVW+I+F, LG+I+G, WAG+I+G, MTREV+I+G, DAYHOFF+I+G, DCMUT+I+G, JTT+I+G, VT+I+G, BLOSUM62+I+G, CPREV+I+G, RTREV+I+G, MTMAM+I+G, MTART+I+G, HIVB+I+G, HIVW+I+G, LG+I+G+F, WAG+I+G+F, MTREV+I+G+F, DAYHOFF+I+G+F, DCMUT+I+G+F, JTT+I+G+F, VT+I+G+F, BLOSUM62+I+G+F, CPREV+I+G+F, RTREV+I+G+F, MTMAM+I+G+F, MTART+I+G+F, HIVB+I+G+F, HIVW+I+G+F
INFO     | 2016-03-08 11:53:57,467 | Setting 'model_selection' to 'aic'
INFO     | 2016-03-08 11:53:57,473 | Setting 'search' to 'greedy'
INFO     | 2016-03-08 11:53:57,474 | ------------------------ BEGINNING NEW RUN -------------------------------
INFO     | 2016-03-08 11:53:57,474 | Looking for alignment file './MAFFT_Urochordate_Panxs_hashed.phy'...
INFO     | 2016-03-08 11:53:57,483 | Using 24 cpus
INFO     | 2016-03-08 11:53:57,483 | Beginning Analysis
INFO     | 2016-03-08 11:53:57,803 | Reading alignment file './MAFFT_Urochordate_Panxs_hashed.phy'
INFO     | 2016-03-08 11:53:57,843 | Starting tree will be estimated from the data.
INFO     | 2016-03-08 11:53:57,843 | Making BioNJ tree for ./analysis/start_tree/filtered_source.phy
INFO     | 2016-03-08 11:53:58,292 | Estimating LG+F branch lengths on tree
INFO     | 2016-03-08 11:53:59,692 | Branchlength estimation finished
INFO     | 2016-03-08 11:53:59,693 | Performing Greedy Analysis
INFO     | 2016-03-08 11:53:59,693 |    *** Analysing starting scheme ***
INFO     | 2016-03-08 11:55:45,355 |       Finished subset 1/1, 100.00 percent done
INFO     | 2016-03-08 11:55:45,359 |    ***Greedy algorithm step 1***
Traceback (most recent call last):
  File "/usr/local/bioinf_tools/partitionfinder_git/PartitionFinderProtein.py", line 23, in <module>
    sys.exit(main.main("PartitionFinderProtein", "protein"))
  File "/usr/local/bioinf_tools/partitionfinder_git/partfinder/main.py", line 399, in main
    run_analysis(cfg, options)
  File "/usr/local/bioinf_tools/partitionfinder_git/partfinder/main.py", line 333, in run_analysis
    results = anal.analyse()
  File "/usr/local/bioinf_tools/partitionfinder_git/partfinder/analysis.py", line 92, in analyse
    self.do_analysis()
  File "/usr/local/bioinf_tools/partitionfinder_git/partfinder/logtools.py", line 159, in indented_fn
    fn(*args, **kwargs)
  File "/usr/local/bioinf_tools/partitionfinder_git/partfinder/analysis_method.py", line 190, in do_analysis
    subsets, the_config, cutoff, d_matrix)
  File "/usr/local/bioinf_tools/partitionfinder_git/partfinder/neighbour.py", line 126, in get_N_closest_subsets
    distance_matrix = get_distance_matrix(subsets, cfg.cluster_weights)
  File "/usr/local/bioinf_tools/partitionfinder_git/partfinder/neighbour.py", line 117, in get_distance_matrix
    final_dists = get_manhattan_matrix(rates, freqs, model, alpha, weights)
  File "/usr/local/bioinf_tools/partitionfinder_git/partfinder/neighbour.py", line 61, in get_manhattan_matrix
    if np.amax(r_dists)>0:
  File "/usr/local/anaconda/envs/py27/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 2263, in amax
    out=out, keepdims=keepdims)
  File "/usr/local/anaconda/envs/py27/lib/python2.7/site-packages/numpy/core/_methods.py", line 26, in _amax
    return umr_maximum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation maximum which has no identity
```

**Comment by roblanf** [comment]
HI @biologyguy, thanks for the pull request! I thought I'd fixed this, but it looks like I undid it. 

I will take a look in the next couple of days, and get it done. I'll also add a test to make sure that I don't undo my fix again...

**Comment by roblanf** [comment]
OK, this is done here: 

https://github.com/brettc/partitionfinder/commit/571a571d7e4e93ab66262f99f4086d556ce1d524

I didn't use your pull request in the end - but I do appreciate the effort. There was a slightly simpler fix. All tests pass (plus the new one for this bug specifically).

**Comment by biologyguy** [comment]
Great! Thanks a million rob.
And also, thanks for the awesome software in general :)
-Steve

**Comment by roblanf** [comment]
Thanks :)

Also note: everything has now moved to the master branch (long overdue, we are moving to continuous integration / delivery).

**Pull request closed without merging**
